### ISSUE TITLE
Test Validation Input Output not working properly

### ISSUE THREAD

**Issue by vivekagal1998** [kyuridenamida/atcoder-tools#165]
The test validation of expected output and received output isn't working properly. Though both of the values are same, still "WA" is being shown.

Figure shown for reference :-
![atcoder](https://user-images.githubusercontent.com/22425848/66830986-59011a00-ef74-11e9-97e3-cf1e6e427fe0.png)

Kindly check and let me know what's the error from my side, if any.

**Comment by kyuridenamida** [comment]
Thanks for reporting the problem and sorry for this late answer.

I suspect the problem is caused by the difference in whether there is a newline (\n) at the end of the line.  The test command currently strictly checks the trailing newline. 

However, I agree it's a little bit unfriendly and maybe we can show a more descriptive error code instead of WA, something like WA_MISSING_NEWLINE.

**Comment by kyuridenamida** [comment]
I tentatively close this issue because I assume there is no more conversation just because 2 months have passed.  Please feel free to re-open when you still have some thoughts on this.
