### ISSUE TITLE
timing is not right

### ISSUE THREAD

**Issue by hackershi** [kyuridenamida/atcoder-tools#184]
if I test with a command , timing is like this

g++ ./oj.cpp -o ./oj  && atcoder-tools test
# in_1.txt ... PASSED 536 ms
# in_2.txt ... PASSED 7 ms
# in_3.txt ... PASSED 4 ms
# in_4.txt ... PASSED 3 ms

but if I first run g++ ./oj.cpp -o ./oj  ,
then atcoder-tools test
# in_1.txt ... PASSED 3 ms
# in_2.txt ... PASSED 3 ms
# in_3.txt ... PASSED 3 ms
# in_4.txt ... PASSED 3 ms

It seems that the timing begins when the  command begins, and ends when first test case ends.
It's troublesome because I use some bash alias for fast typing. The first test case timing is wrong for me. Please fix this bug

**Comment by kyuridenamida** [comment]
Thanks for your report. Unfortunately, I couldn't reproduce the issue on my environment.
Actually I have no idea how the first command affects the second command because the second command never starts until the first command succeeds.  Actually one of my hypotheses was you take an additional a few hundreds of milliseconds before running the compiled exec file in your environment for some reason like a security reason. However, you said running ` g++ ./oj.cpp -o ./oj` `atcoder-tools test` separately worked well... 

Can you check if `g++ ./oj.cpp -o ./oj && time ./oj < {INPUT_FILE}` is also slow? If you confirm it's also slow, unfortunately we have nothing to do on atcoder-tools..

**Comment by hackershi** [comment]
ok, I find out that it's a macbook security issue. The first time the binary tested, the test time is long.

**Comment by kyuridenamida** [comment]
cool. thanks for closing this issue :)
